### PR TITLE
Remove unused dependencies

### PR DESCRIPTION
**Pull request by lpsinger**
@architect/architect has no direct dependencies on the AWS SDK. Only dependent packages like @architect/deploy do.

### We really appreciate your commitment to improving Architect

To maintain a high standard of quality in our releases, before merging every pull request we ask that you've completed the following:

- [x] Forked the repo and created your branch from `master`
- [ ] Made sure tests pass (run `npm it` from the repo root)
- [x] Expanded test coverage related to your changes:
  - [ ] Added and/or updated unit tests (if appropriate)
  - [ ] Added and/or updated integration tests (if appropriate)
- [x] Updated relevant documentation:
  - [ ] Internal to this repo (e.g. `readme.md`, help docs, inline docs & comments, etc.)
  - [ ] [Architect docs (arc.codes)](https://github.com/architect/arc.codes)
- [ ] Summarized your changes in `changelog.md`
- [ ] Linked to any related issues, PRs, etc. below that may relate to, consume, or necessitate these changes

Please also be sure to completed the CLA (if you haven't already).

Learn more about [contributing to Architect here](https://arc.codes/intro/community).

Thanks again!

### CODE REVIEW

**Comment by ryanblock** [comment]
Unfortunately, these packages have to be root dependencies, specifically for Sandbox to properly function. If these deps are not in the root and wind up reified as part of the Sandbox dep tree (`node_modules/@architect/sandbox/node_modules/aws-sdk/`) then Node.js's module resolution won't be able to find the SDK as though it were globally installed in Lambda. Perhaps this could be worked around, but it'd be a lot of work.  What problem are we solving here?

**Comment by lpsinger** [comment]
I wanted to go through and unpin the versions of all of these aws-sdk packages. I thought I would start by removing what seemed like unnecessary dependencies.

**Comment by AlecRust** [comment]
`@architect/architect` now seems to depend on a vulnerable version of `aws-sdk` causing `npm audit fix --force` to install older `@architect/architect@6.0.10`.

**Comment by ryanblock** [comment]
Is there a CVE that affects SDK v2.1055.0? If so where?

**Comment by ryanblock** [comment]
Ok, dug a little deeper, I think we'd all benefit from this issue being taken up with the Lambda team. We intentionally use the version of AWS-SDK they do: v2.1083.0 (ref: https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html)

There is no practical risk of vulnerability from [`xml2js` prototype pollution](https://github.com/advisories/GHSA-776f-qx25-q3cc) in Architect, which runs on your local machine, in CI, etc. Prototype pollution is not a meaningful attack vector for Architect.

Lambda itself, on the other hand, maybe. Practically speaking, probably not – but maybe. So if you'd like to see this changed in Architect, I think we should get it changed in Lambda (which I am all for!).

**Pull request closed without merging**
