### PR TITLE
[WIP] Ensure killed processes return a message to users (fixes #355)

### LINKED ISSUE #355: Sandbox: killed processes will not trigger the timout handler
Found as part of #354.

Simple reproduction case, based on `spawn.js`

Expect a PR shortly.

```
let spawn = require('child_process').spawn
var verySlowNodeCode = "setTimeout(function(){console.log(`Finished`)},20000)"
var log = console.log.bind(console)

var child = spawn('node', ['-e', verySlowNodeCode], { 
    shell: true,
    cwd: 'C:\\Users\\mikem\\OneDrive\\Documents\\appless\\documentdb-arc-test\\src\\http\\get-index',
    env: {}
})


let stdout = ''
let stderr = ''
let timeout = 5000;
// bake a timeout
let to = setTimeout(function () {
    log(`Timed out after ${timeout} ms!`)
    timedout = true
    child.kill()
}, timeout)

child.stdout.on('data', data => {
    log(`Got output data ${data}`)
    // always capture data piped to stdout
    // python buffers so you might get everything despite our best efforts
    stdout += data
})

child.stderr.on('data', data => {
    log(`Got error data ${data}`)
    stderr += data
})

child.on('close', function done (code) {
    log(`Closed!`)
    // Output any console logging from the child process
    
})

child.on('exit', function done (code) {
    log(`Exited!`)
    // Output any console logging from the child process
})
```

### PR DESCRIPTION
**Pull request by mikemaccana**
Fixes #355. Test included.

### CODE REVIEW

**Comment by ryanblock** [comment]
Was going to review this today, but saw you're still pushing to it. Flagged it WIP, lmk when you've got it in a place you're happy with!

**Comment by mikemaccana** [comment]
Ugh I should make more forks. Give me a mo I'll clean up that fork.

**Comment by mikemaccana** [comment]
OK @ryanblock no longer WIP.

**Comment by ryanblock** [comment]
This PR is causing severe sandbox issues for me. Responses are being prepended with:
```
<pre>undefined...__ARC__ 
```
Then followed by response object data.

**Comment by mikemaccana** [comment]
Damn, I'll check it out. Thanks for the heads up.

**Comment by mikemaccana** [comment]
Need to add some working unit tests for existing `spawn` / `invoke` functionality first (which I've tried but had trouble doing). Will fix when I have time.

**Pull request closed without merging**
