### PR TITLE
Fix ws inventory bugs

### PR DESCRIPTION
**Pull request by boldenburg**
* Updates inventory command to be aware of ws functions
* Updates create to ensure lambda packages names are slugs

Tested with the arc-example-ws repository to ensure that the ws functions that get created in AWS are also shown with `npx inventory` and are deleted when you run `npx inventory nuke`.

### CODE REVIEW

**Comment by boldenburg** [comment]
Updated the changelog per https://github.com/architect/architect/commit/a694f5e14d080f6987af8dd83c9271ac0af4db18#r33813630 so users upgrading from older `@ws` installations have an idea of what might be breaking

**Comment by ryanblock** [comment]
This merge unfortunately broke production release of Arc (just hydrate I think); got a fix coming shortly. Since I'm in where: why was it necessary to change the directory structure?

**Comment by mikemaccana** [comment]
So this got merged, but broke stuff - is it fixed? I'd love to move from 5.7 to 5.9.

**Comment by mikemaccana** [comment]
(asking because https://github.com/architect/arc-example-ws/issues/5 just got closed)

**Pull request merged**
